use realEstateTrade;
SELECT * FROM apt_trade_dev;

-- ### 매매가
-- 서울시
SELECT * FROM apt_trade_jongro;
SELECT * FROM apt_trade_junggu;
SELECT * FROM apt_trade_yongsan;
SELECT * FROM apt_trade_seongdong;
SELECT * FROM apt_trade_gwangjin;
SELECT * FROM apt_trade_dongdaemun;
SELECT * FROM apt_trade_jungrang;
SELECT * FROM apt_trade_seongbuk;
SELECT * FROM apt_trade_gangbuk;
SELECT * FROM apt_trade_dobong;
SELECT * FROM apt_trade_nowon;
SELECT * FROM apt_trade_eunpyung;
SELECT * FROM apt_trade_seodaemun;
SELECT * FROM apt_trade_mapo;
SELECT * FROM apt_trade_yangcheon;
SELECT * FROM apt_trade_gangseo;
SELECT * FROM apt_trade_guro;
SELECT * FROM apt_trade_geumchun;
SELECT * FROM apt_trade_yeongdeunpo;
SELECT * FROM apt_trade_dongjak;
SELECT * FROM apt_trade_gwanak;
SELECT * FROM apt_trade_seocho;
SELECT * FROM apt_trade_gangnam;
SELECT * FROM apt_trade_songpa;
SELECT * FROM apt_trade_gangdong;
-- 성남시 분당구
SELECT * FROM apt_trade_bundang;
-- 용인시 수지구
SELECT * FROM apt_trade_suji;

SELECT * FROM apt_rent_jongro;
SELECT * FROM apt_trade_jongro;
DROP TABLE apt_rent_jongro;
RENAME TABLE apt_trade_yeongdeunpo TO apt_trade_yungdeungpo; -- Change a name of table

show databases;

INSERT IGNORE INTO apt_rent_jongro (
        APTNM, BUILDYEAR, CONTRACTTERM, CONTRACTTYPE, DEALDAY, 
        DEALMONTH, DEALYEAR, DEPOSIT, EXCLUUSEAR, FLOOR, 
        JIBUN, MONTHLYRENT, PREDEPOSIT, PREMONTHLYRENT, SGGCD, 
        UMDNM, USERRRIGHT)
        VALUES (1, 1, 1, 1, 1, 
        1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1);

SELECT COLUMN_NAME
	FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
	WHERE TABLE_NAME = 'apt_trade_bundang' 
	AND CONSTRAINT_NAME = 'PRIMARY'
	AND TABLE_SCHEMA = 'realEstateTrade';

INSERT INTO apt_trade_jongro (APTDONG, APTNM, BUILDYEAR, CDEALDAY, CDEALTYPE, 
        DEALAMOUNT, DEALDAY, DEALMONTH, DEALYEAR, DEALINGGBN, EXCLUUSEAR, FLOOR, JIBUN, 
        LANDLEASEHOLDGBN, RGSTDATE, SGGCD, SLERGBN, UMDNM)
        VALUES (' ', '삼전솔하임2차', 2012, ' ', ' ', '13,500', 13, 10, 2022, '중개거래', 16.67, 5, '296-19', 'N', ' ', 11110, ' ', '숭인동');

SELECT * FROM apt_rent_jongro WHERE DEALYEAR=2024 AND DEALMONTH=11;
DELETE FROM apt_trade_jongro WHERE id=5;
TRUNCATE TABLE apt_trade_seongdong;
SELECT COUNT(*) FROM apt_trade_songpa;
DROP TABLE apt_trade_seongdong;
ALTER TABLE apt_trade_seongdong ADD UNIQUE (APTDONG(10), APTNM(100), EXCLUUSEAR(100), UMDNM(100), JIBUN(100), DEALMONTH(10), DEALYEAR(10), DEALDAY(10), DEALAMOUNT(100), CDEALDAY(20), CDEALTYPE(10));

-- aptNm + excluUseAr + umdNm + jibun + DEALMONTH + DEALYEAR

CREATE TABLE apt_trade_yeongdeungpo (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    APTDONG VARCHAR(255),
    APTNM VARCHAR(255),
    BUILDYEAR VARCHAR(255),
    CDEALDAY VARCHAR(255),
    CDEALTYPE VARCHAR(255),
    DEALAMOUNT VARCHAR(255),
    DEALDAY VARCHAR(255),
    DEALMONTH VARCHAR(255),
    DEALYEAR VARCHAR(255),
    DEALINGGBN VARCHAR(255),
    EXCLUUSEAR VARCHAR(255),
    FLOOR VARCHAR(255),
    JIBUN VARCHAR(255),
    LANDLEASEHOLDGBN VARCHAR(255),
    RGSTDATE VARCHAR(255),
    SGGCD VARCHAR(255),
    SLERGBN VARCHAR(255),
    UMDNM VARCHAR(255),
    PRIMARY KEY (id),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (APTDONG(50), APTNM(100), EXCLUUSEAR(100), UMDNM(100), JIBUN(100), DEALMONTH(10), DEALYEAR(10), DEALDAY(10), DEALAMOUNT(100), CDEALDAY(20), CDEALTYPE(10))
);

CREATE TABLE apt_rent_jongro (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    APTNM VARCHAR(255),
    BUILDYEAR VARCHAR(255),
    CONTRACTTERM VARCHAR(255),
    CONTRACTTYPE VARCHAR(255),
    DEALDAY VARCHAR(255),
    DEALMONTH VARCHAR(255),
    DEALYEAR VARCHAR(255),
    DEPOSIT VARCHAR(255),
    EXCLUUSEAR VARCHAR(255),
    FLOOR VARCHAR(255),
    JIBUN VARCHAR(255),
    MONTHLYRENT VARCHAR(255),
    PREDEPOSIT VARCHAR(255),
    PREMONTHLYRENT VARCHAR(255),
    SGGCD VARCHAR(255),
    UMDNM VARCHAR(255),
    USERRRIGHT VARCHAR(255),
    PRIMARY KEY (id),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (APTNM(100), EXCLUUSEAR(100), UMDNM(100), JIBUN(100), DEALMONTH(10), DEALYEAR(10), DEALDAY(10), FLOOR(10), DEPOSIT(100)));

ALTER TABLE apt_trade ADD PRIMARY KEY (id);
SELECT * FROM apt_trade_songpa WHERE APTNM='주공아파트 5단지' AND EXCLUUSEAR='76.5'; 

ALTER TABLE apt_trade_yeongdeungpo
ADD APTSEQ VARCHAR(20), 
ADD BONBUN VARCHAR(10), 
ADD BUBUN VARCHAR(10), 
ADD LANDCD VARCHAR(10), 
ADD ROADNM VARCHAR(20), 
ADD ROADNMBONBUN VARCHAR(20), 
ADD ROADNMBUBUN VARCHAR(20), 
ADD ROADNMCD VARCHAR(10), 
ADD ROADNMSEQ VARCHAR(10), 
ADD ROADNMSGGCD VARCHAR(10), 
ADD UMDCD VARCHAR(10);

SHOW INDEX FROM apt_trade;


DELETE FROM apt_trade_songpa; 
SELECT * FROM apt_trade_seodaemun;
SELECT COUNT(*) FROM apt_trade_seodaemun;
SELECT DEALMONTH, DEALYEAR FROM apt_trade_seodaemun GROUP BY DEALMONTH, DEALYEAR;

SELECT APTNM FROM apt_trade GROUP BY APTNM;

SELECT * FROM apt_trade WHERE APTNM IN (SELECT APTNM FROM apt_trade GROUP BY APTNM);
SELECT DISTINCT APTNM, EXCLUUSEAR, UMDNM, JIBUN FROM apt_trade;
SELECT COUNT(*) FROM (SELECT DISTINCT APTNM, EXCLUUSEAR, UMDNM, JIBUN FROM apt_trade) AS sub;
SELECT * FROM apt_trade WHERE DEALMONTH='9' AND DEALYEAR='2024';
SELECT COUNT(*) FROM (SELECT * FROM apt_trade WHERE DEALMONTH='9' AND DEALYEAR='2024') AS COUNT;
SELECT DISTINCT DEALMONTH, DEALYEAR FROM apt_trade;

SELECT DEALAMOUNT FROM apt_trade WHERE APTNM='대우' AND EXCLUUSEAR='114.71' AND UMDNM='금호동4가' AND JIBUN='800' AND DEALMONTH='5' AND DEALYEAR='2022';

CREATE TABLE apt_details (
detail_id bigint(20) AUTO_INCREMENT PRIMARY KEY,
id bigint(20),
APTNM varchar(255),
EXCLUUSEAR varchar(255),
UMDNM varchar(255),
JIBUN varchar(255),
FOREIGN KEY (id) REFERENCES apt_trade(id)
);

SELECT * FROM apt_trade
WHERE ABS((SELECT DEALAMOUNT FROM apt_trade WHERE APTNM='대우' AND EXCLUUSEAR='114.71' AND UMDNM='금호동4가' AND JIBUN='800' AND DEALMONTH='5' AND DEALYEAR='2022')
-  (SELECT DEALAMOUNT FROM apt_trade WHERE APTNM='대우' AND EXCLUUSEAR='114.71' AND UMDNM='금호동4가' AND JIBUN='800' AND DEALMONTH='8' AND DEALYEAR='2024'))>1;

-- 2022년 10월 매매가랑 2024년 9월 매매가 차이가 1억 이하인거 --
SELECT t1.id, t2.id AS id2, t1.APTNM, t2.APTNM AS APTNM2, t1.EXCLUUSEAR, t2.EXCLUUSEAR AS EXCLUUSEAR2, t1.UMDNM, t2.UMDNM AS UMDNM2, t1.JIBUN, t2.JIBUN AS JIBUN2, t1.DEALAMOUNT, t2.DEALAMOUNT AS DEALAMOUNT2, t1.DEALYEAR, t1.DEALMONTH, t2.DEALYEAR AS DEALYEAR2, t2.DEALMONTH AS DEALMONTH2
FROM apt_trade_gangnam t1
JOIN apt_trade_gangnam t2 ON t1.APTNM = t2.APTNM AND t1.EXCLUUSEAR = t2.EXCLUUSEAR AND t1.UMDNM = t2.UMDNM AND t1.JIBUN = t2.JIBUN
WHERE t1.id != t2.id
AND t1.DEALYEAR = 2022
AND t1.DEALMONTH = 12 
AND t2.DEALYEAR = 2024
AND t2.DEALMONTH = 10
AND ABS(t1.DEALAMOUNT - t2.DEALAMOUNT) <= 10000;

SELECT * FROM apt_trade_songpa WHERE DEALYEAR=2024 AND DEALMONTH=11;
SET SQL_SAFE_UPDATES = 0;
DELETE FROM apt_trade_jongro; 
SELECT * FROM apt_rent_suji WHERE DEALYEAR=2024 AND DEALMONTH=11;

-- 매매가-전세가 <= 2억 -- 
SELECT t1.id, t2.id AS id2,t1.APTNM, t1.JIBUN, t1.UMDNM, t1.EXCLUUSEAR, t2.EXCLUUSEAR, t1.DEALAMOUNT, t2.DEPOSIT, t2.MONTHLYRENT, 
ABS(CAST(REPLACE(t1.DEALAMOUNT,',','') AS SIGNED) - CAST(REPLACE(t2.DEPOSIT,',','') AS SIGNED)) AS DIFF
FROM apt_trade_suji t1, apt_rent_suji t2
WHERE (t1.APTNM = t2.APTNM AND t1.EXCLUUSEAR = t2.EXCLUUSEAR AND t1.UMDNM = t2.UMDNM AND t1.JIBUN = t2.JIBUN)
AND t1.DEALYEAR=2024 AND t1.DEALMONTH=11
AND t2.DEALYEAR=2024 AND t2.DEALMONTH=11
AND ABS(CAST(REPLACE(t1.DEALAMOUNT,',','') AS SIGNED) - CAST(REPLACE(t2.DEPOSIT,',','') AS SIGNED)) <= 25000
AND t2.MONTHLYRENT=0;

# 최종
SELECT t1.id, t2.id AS id2, t1.APTNM, t2.APTNM AS APTNM2, t1.EXCLUUSEAR, t2.EXCLUUSEAR AS EXCLUUSEAR2, t1.UMDNM, t2.UMDNM AS UMDNM2, t1.JIBUN, t2.JIBUN AS JIBUN2, 
t1.DEALAMOUNT, t2.DEALAMOUNT AS DEALAMOUNT2, 
ABS(CAST(REPLACE(t1.DEALAMOUNT,',','') AS SIGNED) - CAST(REPLACE(t2.DEALAMOUNT,',','') AS SIGNED)) AS DIFF, 
t1.DEALYEAR, t1.DEALMONTH, t2.DEALYEAR AS DEALYEAR2, t2.DEALMONTH AS DEALMONTH2
FROM apt_trade_gangnam t1
JOIN apt_trade_gangnam t2 ON t1.APTNM = t2.APTNM AND t1.EXCLUUSEAR = t2.EXCLUUSEAR AND t1.UMDNM = t2.UMDNM AND t1.JIBUN = t2.JIBUN
WHERE t1.id != t2.id
AND ((t1.DEALYEAR = 2022 AND t1.DEALMONTH >= 10)
OR (t1.DEALYEAR = 2023 AND t1.DEALMONTH <= 3))
AND t2.DEALYEAR = 2024
AND t2.DEALMONTH = 10
AND ABS(CAST(REPLACE(t1.DEALAMOUNT,',','') AS SIGNED) - CAST(REPLACE(t2.DEALAMOUNT,',','') AS SIGNED)) <= 10000;

SELECT ABS(CAST("145000" AS SIGNED) - CAST("142900" AS SIGNED));
SELECT * FROM apt_trade_gangnam WHERE DEALYEAR=2024 AND DEALMONTH=10;

SELECT t1.APTNM, t2.APTNM, t1.DEALYEAR, t1.DEALMONTH, t2.DEALYEAR, t2.DEALMONTH, t1.DEALAMOUNT, t2.DEALAMOUNT
FROM apt_trade t1
JOIN apt_trade t2 ON t1.APTNM = t2.APTNM AND t1.EXCLUUSEAR = t2.EXCLUUSEAR AND t1.UMDNM = t2.UMDNM AND t1.JIBUN = t2.JIBUN
WHERE t1.id != t2.id
AND t1.DEALYEAR = 2022 
AND t1.DEALMONTH = 10
AND t2.DEALYEAR = 2024
AND t2.DEALMONTH = 9;

SELECT t1.id, t2.id, t1.APTNM, t2.APTNM, t1.DEALYEAR, t1.DEALMONTH, t2.DEALYEAR, t2.DEALMONTH, t1.DEALAMOUNT, t2.DEALAMOUNT
FROM apt_trade t1
JOIN apt_trade t2 ON t1.APTNM = t2.APTNM AND t1.EXCLUUSEAR = t2.EXCLUUSEAR AND t1.UMDNM = t2.UMDNM AND t1.JIBUN = t2.JIBUN
WHERE t1.id != t2.id
AND t1.DEALYEAR = 2024
AND t1.DEALMONTH = 9
;

SELECT * FROM apt_trade_seongdong WHERE DEALYEAR=2024;

SELECT t1.id, t2.id AS id2, t1.APTNM, t2.APTNM AS APTNM2, t1.EXCLUUSEAR, t2.EXCLUUSEAR AS EXCLUUSEAR2, 
        t1.UMDNM, t2.UMDNM AS UMDNM2, t1.JIBUN, t2.JIBUN AS JIBUN2, t1.DEALAMOUNT, t2.DEALAMOUNT AS DEALAMOUNT2, 
        ABS(CAST(REPLACE(t1.DEALAMOUNT,',','') AS SIGNED) - CAST(REPLACE(t2.DEALAMOUNT,',','') AS SIGNED)) AS DIFF, 
        t1.DEALYEAR, t1.DEALMONTH, t2.DEALYEAR AS DEALYEAR2, t2.DEALMONTH AS DEALMONTH2
        FROM apt_trade_seongdong t1
        JOIN apt_trade_seongdong t2 ON t1.APTNM = t2.APTNM AND t1.EXCLUUSEAR = t2.EXCLUUSEAR AND t1.UMDNM = t2.UMDNM AND t1.JIBUN = t2.JIBUN
        WHERE t1.id != t2.id
        AND ((t1.DEALYEAR = 2022 AND t1.DEALMONTH >= 10)
        OR (t1.DEALYEAR = 2023 AND t1.DEALMONTH <= 3))
        AND t2.DEALYEAR = 2024
        AND t2.DEALMONTH = 10
        AND ABS(CAST(REPLACE(t1.DEALAMOUNT,',','') AS SIGNED) - CAST(REPLACE(t2.DEALAMOUNT,',','') AS SIGNED)) <= 10000;
\
