# Generated by Django 5.1.1 on 2024-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptTrade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aptdong', models.CharField(blank=True, db_column='APTDONG', max_length=255, null=True)),
                ('aptnm', models.CharField(blank=True, db_column='APTNM', max_length=255, null=True)),
                ('buildyear', models.CharField(blank=True, db_column='BUILDYEAR', max_length=255, null=True)),
                ('cdealday', models.CharField(blank=True, db_column='CDEALDAY', max_length=255, null=True)),
                ('cdealtype', models.CharField(blank=True, db_column='CDEALTYPE', max_length=255, null=True)),
                ('dealamount', models.CharField(blank=True, db_column='DEALAMOUNT', max_length=255, null=True)),
                ('dealday', models.CharField(blank=True, db_column='DEALDAY', max_length=255, null=True)),
                ('dealmonth', models.CharField(blank=True, db_column='DEALMONTH', max_length=255, null=True)),
                ('dealyear', models.CharField(blank=True, db_column='DEALYEAR', max_length=255, null=True)),
                ('dealinggbn', models.CharField(blank=True, db_column='DEALINGGBN', max_length=255, null=True)),
                ('excluusear', models.CharField(blank=True, db_column='EXCLUUSEAR', max_length=255, null=True)),
                ('floor', models.CharField(blank=True, db_column='FLOOR', max_length=255, null=True)),
                ('jibun', models.CharField(blank=True, db_column='JIBUN', max_length=255, null=True)),
                ('landleaseholdgbn', models.CharField(blank=True, db_column='LANDLEASEHOLDGBN', max_length=255, null=True)),
                ('rgstdate', models.CharField(blank=True, db_column='RGSTDATE', max_length=255, null=True)),
                ('sggcd', models.CharField(blank=True, db_column='SGGCD', max_length=255, null=True)),
                ('slergbn', models.CharField(blank=True, db_column='SLERGBN', max_length=255, null=True)),
                ('umdnm', models.CharField(blank=True, db_column='UMDNM', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apt_trade',
                'managed': False,
            },
        ),
    ]
